aws_region="us-east-1"
function_name="codedeploy_slack_notifier_lambda"
handler="lambda.lambda_handler"
runtime="python3.6"
slack_hook_url="https://hooks.slack.com/services/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"
slackChannel="#devops"
organization="carbangla"